build:
	docker build -t asia-docker.pkg.dev/${GCP_PROJECT_ID}/prefect-repository/custom-image:latest -f Dockerfile.custom .

push:
	docker push asia-docker.pkg.dev/${GCP_PROJECT_ID}/prefect-repository/custom-image:latest
